//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.8941
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此原始程式碼由 wsdl 版本=2.0.50727.3038 自動產生。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "AMS_WebIFSoap", Namespace = "http://AMS_Web_Server")]
public partial class AMS_WebIF : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback AlarmSendWithParamOperationCompleted;

    private System.Threading.SendOrPostCallback AlarmTerminateOperationCompleted;

    private System.Threading.SendOrPostCallback CheckAliveOperationCompleted;

    /// <remarks/>
    public AMS_WebIF()
    {
        //this.Url = "http://192.168.56.1:3450/AMS_Web_Server/AMS_WebIF.asmx";
        this.Url = "http://localhost:3455/AMS_Web_Server/AMS_WebIF.asmx";
    }

    /// <remarks/>
    public event AlarmSendWithParamCompletedEventHandler AlarmSendWithParamCompleted;

    /// <remarks/>
    public event AlarmTerminateCompletedEventHandler AlarmTerminateCompleted;

    /// <remarks/>
    public event CheckAliveCompletedEventHandler CheckAliveCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AMS_Web_Server/AlarmSendWithParam", RequestNamespace = "http://AMS_Web_Server", ResponseNamespace = "http://AMS_Web_Server", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ReturnMessage AlarmSendWithParam(AlarmSendWithParamMessage alarmSendWithParamMessage)
    {
        object[] results = this.Invoke("AlarmSendWithParam", new object[] {
                    alarmSendWithParamMessage});
        return ((ReturnMessage)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginAlarmSendWithParam(AlarmSendWithParamMessage alarmSendWithParamMessage, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("AlarmSendWithParam", new object[] {
                    alarmSendWithParamMessage}, callback, asyncState);
    }

    /// <remarks/>
    public ReturnMessage EndAlarmSendWithParam(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ReturnMessage)(results[0]));
    }

    /// <remarks/>
    public void AlarmSendWithParamAsync(AlarmSendWithParamMessage alarmSendWithParamMessage)
    {
        this.AlarmSendWithParamAsync(alarmSendWithParamMessage, null);
    }

    /// <remarks/>
    public void AlarmSendWithParamAsync(AlarmSendWithParamMessage alarmSendWithParamMessage, object userState)
    {
        if ((this.AlarmSendWithParamOperationCompleted == null))
        {
            this.AlarmSendWithParamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlarmSendWithParamOperationCompleted);
        }
        this.InvokeAsync("AlarmSendWithParam", new object[] {
                    alarmSendWithParamMessage}, this.AlarmSendWithParamOperationCompleted, userState);
    }

    private void OnAlarmSendWithParamOperationCompleted(object arg)
    {
        if ((this.AlarmSendWithParamCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AlarmSendWithParamCompleted(this, new AlarmSendWithParamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AMS_Web_Server/AlarmTerminate", RequestNamespace = "http://AMS_Web_Server", ResponseNamespace = "http://AMS_Web_Server", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ReturnMessage AlarmTerminate(AlarmTerminateInfo alarmTerminateInfo)
    {
        object[] results = this.Invoke("AlarmTerminate", new object[] { alarmTerminateInfo});
        return ((ReturnMessage)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginAlarmTerminate(AlarmTerminateInfo alarmTerminateInfo, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("AlarmTerminate", new object[] {
                    alarmTerminateInfo}, callback, asyncState);
    }

    /// <remarks/>
    public ReturnMessage EndAlarmTerminate(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ReturnMessage)(results[0]));
    }

    /// <remarks/>
    public void AlarmTerminateAsync(AlarmTerminateInfo alarmTerminateInfo)
    {
        this.AlarmTerminateAsync(alarmTerminateInfo, null);
    }

    /// <remarks/>
    public void AlarmTerminateAsync(AlarmTerminateInfo alarmTerminateInfo, object userState)
    {
        if ((this.AlarmTerminateOperationCompleted == null))
        {
            this.AlarmTerminateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlarmTerminateOperationCompleted);
        }
        this.InvokeAsync("AlarmTerminate", new object[] {
                    alarmTerminateInfo}, this.AlarmTerminateOperationCompleted, userState);
    }

    private void OnAlarmTerminateOperationCompleted(object arg)
    {
        if ((this.AlarmTerminateCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AlarmTerminateCompleted(this, new AlarmTerminateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://AMS_Web_Server/CheckAlive", RequestNamespace = "http://AMS_Web_Server", ResponseNamespace = "http://AMS_Web_Server", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CheckAlive()
    {
        object[] results = this.Invoke("CheckAlive", new object[0]);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCheckAlive(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CheckAlive", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public bool EndCheckAlive(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void CheckAliveAsync()
    {
        this.CheckAliveAsync(null);
    }

    /// <remarks/>
    public void CheckAliveAsync(object userState)
    {
        if ((this.CheckAliveOperationCompleted == null))
        {
            this.CheckAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckAliveOperationCompleted);
        }
        this.InvokeAsync("CheckAlive", new object[0], this.CheckAliveOperationCompleted, userState);
    }

    private void OnCheckAliveOperationCompleted(object arg)
    {
        if ((this.CheckAliveCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckAliveCompleted(this, new CheckAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://AMS_Web_Server")]
public partial class AlarmSendWithParamMessage
{

    private string factoryIDField;

    private string subSystemIDField;

    private string eqpIDField;

    private string alarmInfoIDField;

    private string alarmSubjectField;

    private string alarmContentField;

    private string alarmContentTypeField;

    private string receiveTypeField;

    private string filterParamField;

    private string infoParamField;

    /// <remarks/>
    public string FactoryID
    {
        get
        {
            return this.factoryIDField;
        }
        set
        {
            this.factoryIDField = value;
        }
    }

    /// <remarks/>
    public string SubSystemID
    {
        get
        {
            return this.subSystemIDField;
        }
        set
        {
            this.subSystemIDField = value;
        }
    }

    /// <remarks/>
    public string EqpID
    {
        get
        {
            return this.eqpIDField;
        }
        set
        {
            this.eqpIDField = value;
        }
    }

    /// <remarks/>
    public string AlarmInfoID
    {
        get
        {
            return this.alarmInfoIDField;
        }
        set
        {
            this.alarmInfoIDField = value;
        }
    }

    /// <remarks/>
    public string AlarmSubject
    {
        get
        {
            return this.alarmSubjectField;
        }
        set
        {
            this.alarmSubjectField = value;
        }
    }

    /// <remarks/>
    public string AlarmContent
    {
        get
        {
            return this.alarmContentField;
        }
        set
        {
            this.alarmContentField = value;
        }
    }

    /// <remarks/>
    public string AlarmContentType
    {
        get
        {
            return this.alarmContentTypeField;
        }
        set
        {
            this.alarmContentTypeField = value;
        }
    }

    /// <remarks/>
    public string ReceiveType
    {
        get
        {
            return this.receiveTypeField;
        }
        set
        {
            this.receiveTypeField = value;
        }
    }

    /// <remarks/>
    public string FilterParam
    {
        get
        {
            return this.filterParamField;
        }
        set
        {
            this.filterParamField = value;
        }
    }

    /// <remarks/>
    public string InfoParam
    {
        get
        {
            return this.infoParamField;
        }
        set
        {
            this.infoParamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://AMS_Web_Server")]
public partial class AlarmTerminateInfo
{

    private string factoryIDField;

    private string subSystemIDField;

    private string eqpIDField;

    private string alarmInfoIDField;

    private string filterParamField;

    /// <remarks/>
    public string FactoryID
    {
        get
        {
            return this.factoryIDField;
        }
        set
        {
            this.factoryIDField = value;
        }
    }

    /// <remarks/>
    public string SubSystemID
    {
        get
        {
            return this.subSystemIDField;
        }
        set
        {
            this.subSystemIDField = value;
        }
    }

    /// <remarks/>
    public string EqpID
    {
        get
        {
            return this.eqpIDField;
        }
        set
        {
            this.eqpIDField = value;
        }
    }

    /// <remarks/>
    public string AlarmInfoID
    {
        get
        {
            return this.alarmInfoIDField;
        }
        set
        {
            this.alarmInfoIDField = value;
        }
    }

    /// <remarks/>
    public string FilterParam
    {
        get
        {
            return this.filterParamField;
        }
        set
        {
            this.filterParamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://AMS_Web_Server")]
public partial class ReturnMessage
{

    private string returnCodeField;

    private string returnErrorMessageField;

    private ReturnStatus returnStatusField;

    /// <remarks/>
    public string ReturnCode
    {
        get
        {
            return this.returnCodeField;
        }
        set
        {
            this.returnCodeField = value;
        }
    }

    /// <remarks/>
    public string ReturnErrorMessage
    {
        get
        {
            return this.returnErrorMessageField;
        }
        set
        {
            this.returnErrorMessageField = value;
        }
    }

    /// <remarks/>
    public ReturnStatus returnStatus
    {
        get
        {
            return this.returnStatusField;
        }
        set
        {
            this.returnStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://AMS_Web_Server")]
public enum ReturnStatus
{

    /// <remarks/>
    OK,

    /// <remarks/>
    NG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void AlarmSendWithParamCompletedEventHandler(object sender, AlarmSendWithParamCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AlarmSendWithParamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal AlarmSendWithParamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ReturnMessage Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ReturnMessage)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void AlarmTerminateCompletedEventHandler(object sender, AlarmTerminateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AlarmTerminateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal AlarmTerminateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ReturnMessage Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ReturnMessage)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void CheckAliveCompletedEventHandler(object sender, CheckAliveCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CheckAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
